package top.jnaw.jee.platform.model;

import top.jnaw.jee.platform.model.base.BaseDepartmentsUsers;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DepartmentsUsers extends BaseDepartmentsUsers<DepartmentsUsers> {
	public static final DepartmentsUsers dao = new DepartmentsUsers().dao();
}
