package top.jnaw.jee.platform.model;

import top.jnaw.jee.platform.model.base.BaseOpinion;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Opinion extends BaseOpinion<Opinion> {
	public static final Opinion dao = new Opinion().dao();

//	public
}
