package top.jnaw.jee.platform.model;

import top.jnaw.jee.platform.model.base.BaseRolesPermissions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class RolesPermissions extends BaseRolesPermissions<RolesPermissions> {
	public static final RolesPermissions dao = new RolesPermissions().dao();
}
