package top.jnaw.jee.platform.model;

import top.jnaw.jee.platform.model.base.BaseUserRoles;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserRoles extends BaseUserRoles<UserRoles> {
	public static final UserRoles dao = new UserRoles().dao();
}
