package top.jnaw.jee.platform.model;

import com.jfinal.plugin.activerecord.Db;

import java.util.List;
import javax.xml.ws.soap.Addressing;
import top.jnaw.jee.platform.model.base.BaseUserTeam;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UserTeam extends BaseUserTeam<UserTeam> {
  public static final UserTeam dao = new UserTeam().dao();

  public boolean deleteUser(String tno) {
    String sql = "delete from user_team where tno = '" + tno + "'";
    int a = Db.update(sql);
    return true;
  }

  public boolean delUserBytUidAndTno(int uid,String tno) {
    String sql = "delete from user_team where tno = ? and uid = ?";
    int a = Db.update(sql,tno,uid);
    return true;
  }


  /**
   * 通过群号查人
   * @param no
   * @return
   */
  public List<UserTeam> findPeopleByNo(int no){
    return UserTeam.dao.find("select * from user_team where tno=?",no);
  }

  public boolean add(int uid,String no){
    String sql = "INSERT IGNORE INTO user_team (uid, tno) VALUES (?, ?)";
    if (Db.update(sql,uid,no)>0){
     return true;
    }else {
      return false;
    }
  }

  //TODO 添加查询其他人需要的接口（还没问）

}
